controller_list:
  - name: right_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - right_arm_shoulder_roll_joint
      - right_arm_shoulder_pitch_joint
      - right_arm_shoulder_yaw_joint
      - right_arm_elbow_pitch_joint
      - right_arm_elbow_yaw_joint
      - right_arm_wrist_pitch_joint
      - right_arm_wrist_roll_joint
  - name: left_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - left_arm_shoulder_roll_joint
      - left_arm_shoulder_pitch_joint
      - left_arm_shoulder_yaw_joint
      - left_arm_elbow_pitch_joint
      - left_arm_elbow_yaw_joint
      - left_arm_wrist_pitch_joint
      - left_arm_wrist_roll_joint
